# Generated by Django 4.1.1 on 2022-09-09 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id_livro', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('qnt_pag', models.IntegerField()),
                ('editora', models.CharField(max_length=50)),
                ('ano_publi', models.DateField(max_length=4)),
                ('nota', models.IntegerField(max_length=2)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('emprestado', models.BooleanField(default=False)),
                ('nome_emprestado', models.CharField(max_length=50)),
                ('data_emprestimo', models.DateTimeField()),
                ('data_devolucao', models.DateTimeField()),
            ],
        ),
    ]
