# Generated by Django 4.1.1 on 2022-09-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0006_alter_livros_ano_publi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='ano_publi',
            field=models.CharField(max_length=10),
        ),
    ]
