# Generated by Django 4.1.1 on 2022-09-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0007_alter_livros_ano_publi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='id_livro',
        ),
        migrations.AddField(
            model_name='livros',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
