# Generated by Django 4.1.1 on 2022-09-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0010_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='avaliacao',
            field=models.CharField(choices=[('P', 'Péssimo'), ('R', 'Ruim'), ('B', 'Bom'), ('O', 'Ótimo')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
