# Generated by Django 4.1.1 on 2022-09-26 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0014_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='capa_livro'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 9, 43, 17, 654551)),
        ),
    ]
