# Generated by Django 4.1.1 on 2022-09-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='complemento',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nas',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='instagram',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rua',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='whatsapp',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
