# Generated by Django 4.1.1 on 2022-09-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_bairro_usuario_cep_usuario_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=10),
        ),
    ]
